// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn4tk8TxVR9p3zOaUxxm9W-9wHVXCQawQ',
    appId: '1:683453924488:web:c66003404ae93e5efc4b3d',
    messagingSenderId: '683453924488',
    projectId: 'taskify-app-2026',
    authDomain: 'taskify-app-2026.firebaseapp.com',
    storageBucket: 'taskify-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdhk9wb20IlHmpmM2dFBWRCs4CS3MYxM',
    appId: '1:683453924488:android:aad6772a892a075efc4b3d',
    messagingSenderId: '683453924488',
    projectId: 'taskify-app-2026',
    storageBucket: 'taskify-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzjv5EuMPZtKjF2w5sSo0NGhpTcjjBAd0',
    appId: '1:683453924488:ios:70a6d236bc7e9050fc4b3d',
    messagingSenderId: '683453924488',
    projectId: 'taskify-app-2026',
    storageBucket: 'taskify-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.taski',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzjv5EuMPZtKjF2w5sSo0NGhpTcjjBAd0',
    appId: '1:683453924488:ios:70a6d236bc7e9050fc4b3d',
    messagingSenderId: '683453924488',
    projectId: 'taskify-app-2026',
    storageBucket: 'taskify-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.taski',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn4tk8TxVR9p3zOaUxxm9W-9wHVXCQawQ',
    appId: '1:683453924488:web:fde9cb2612babb74fc4b3d',
    messagingSenderId: '683453924488',
    projectId: 'taskify-app-2026',
    authDomain: 'taskify-app-2026.firebaseapp.com',
    storageBucket: 'taskify-app-2026.firebasestorage.app',
  );
}
